version: "3"
services:
  satisfactory-server:
    container_name: "satisfactory"
    hostname: "satisfactory"
    image: "wolveix/satisfactory-server:latest"
    ports:
      - "7777:7777/udp"
      - "15000:15000/udp"
      - "15777:15777/udp"
    volumes:
      - "/home/user/satisfactory/config:/config"
    environment:
      - AUTOPAUSE=false
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 16G
    #     reservations:
    #       memory: 12G
